# Pinhole Camera Model Practice Questions

## Question 1: Perspective Projection

A 3D point in the camera coordinate system is given by `p_c = [10, 5, 20]`. 
The camera has a focal length `f` of 50mm. 
Calculate the position of the projection of this point on the image plane in meters.

In [5]:
# p_c = [10,5,20]
pcx=10
pcy=5
pcz=20
f=0.05
ucm = f*(pcx/pcz)
vcm = f*(pcy/pcz)
print(ucm,vcm)

0.025 0.0125


---

## Question 2: Conversion to Pixels

Given the projected point from Question 1, convert its coordinates from meters to pixels. 
Assume the following intrinsic parameters: 
- `s_x` = 800 pixels/meter
- `s_y` = 800 pixels/meter
- `o_x` = 320 pixels
- `o_y` = 240 pixels
What are the pixel coordinates `(u^I, v^I)`?

In [6]:
sx=800
sy=800
ox=320
oy=240
uI=(sx*ucm)+ox
yI=(sy*ucm)+oy
print(uI,yI)

340.0 260.0


---

## Question 3: Intrinsic Matrix

Construct the intrinsic calibration matrix `K` using the parameters from Question 2, assuming no skew (`s_θ = 0`).

In [7]:
k = [
        [sx*f, 0, ox],
        [0, sy*f, oy],
        [0, 0, 1]
]
print(k)

[[40.0, 0, 320], [0, 40.0, 240], [0, 0, 1]]


---

## Question 4: Point Projection with Known Pose

A point in the world frame is given by `p_w = [2, 3, 50]`. The camera's pose `T_w^c` is given by an identity rotation matrix and a translation vector `t_w^c = [0, 0, 10]`. [cite_start]Using the intrinsic matrix `K` from Question 3, calculate the pixel coordinates of the projected point. [cite: 14, 16, 17]

In [31]:
import numpy as np

p_w=[2, 3, 50,1]
t_wc = np.array([0, 0, 10]).reshape(3, 1)   # or: t_wc = np.array([[0],[0],[10]])
r_wc = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

T_wc = np.hstack((r_wc, t_wc))   # 3×4 pose matrix
ans = np.matmul(k,T_wc)
ans = np.matmul(ans,p_w)
print(ans)
print(ans/60)

[19280. 14520.    60.]
[321.33333333 242.           1.        ]


---

## Question 5: Radial Distortion

A point is projected on the image plane at `(u_distort^I, v_distort^I) = (400, 350)` including radial distortion. Given distortion coefficients `a1 = 0.0001` and `a2 = 0.0000002` and the principal point `(o_x, o_y) = (320, 240)`, calculate the corrected pixel coordinates `(u^I, v^I)`.

In [4]:
udistort=400
vdistort=350
a1=0.0001
a2=0.0000002
ox=320
oy=240
r=136.014705087
uI = (1 + (a1*r**2) + (a2*r**4))*(udistort-ox)+ox
vI = (1 + (a1*r**2) + (a2*r**4))*(vdistort-oy)+oy
print(uI, vI)            

6023.9999999421525 8082.999999920459
